<div class="wrap">
    <div class="clear"></div>
    <h1>PRO plan offers:</h1>
    <p style="font-size:16px; max-width:68%;">Organize your FAQ content with precision using the Pro version of CM FAQ. The FAQ Lists feature lets you group multiple FAQ categories into comprehensive lists for better management and presentation.</p>
    <br>
    <div style="float:left; width:100%; margin-bottom:30px;">
        <div style="text-align:center; width:300px; float:left; margin-right:20px;">
            <a href="<?php echo CMFAQ_PLUGIN_DIR_URL . 'assets/backend/img/cm-faq-pro-lists.png'; ?>"
               target="_blank" style="text-decoration:none;">
                <img src="<?php echo CMFAQ_PLUGIN_DIR_URL . 'assets/backend/img/cm-faq-pro-lists.png'; ?>"
                     alt="" style="width:100%; border:1px solid #444;"/>
            </a>
            <span style="font-size:15px;">FAQ Lists</span>
        </div>
    </div>
    <br>
    <h3>Upgrade to Pro for:</h3>
    <ul style="font-size:16px;">
        <li>
            <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor"
                 viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;">
                <path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>
            Grouping FAQ categories into organized lists.
        </li>
        <li>
            <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor"
                 viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;">
                <path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>
            Enhancing user navigation with structured content.
        </li>
        <li>
            <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor"
                 viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;">
                <path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>
            Managing FAQs efficiently with categorized lists.
        </li>
    </ul>
    <br>
    <a href="<?php echo admin_url('admin.php?page=cmfaq_pro'); ?>"
       style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>
</div>