<div class="wrap">
    <div class="clear"></div>
    <h1>PRO plan offers:</h1>
    <p style="font-size:16px; max-width:70%;">Gain deeper insights into your FAQ performance with the Pro version of CM FAQ. The Statistics feature tracks views and votes, providing actionable data for optimizing your FAQs.</p>
    <br>
    <div style="float:left; width:100%; margin-bottom:30px;">
        <div style="text-align:center; width:300px; float:left; margin-right:20px;">
            <a href="<?php echo CMFAQ_PLUGIN_DIR_URL . 'assets/backend/img/cm-faq-pro-statistics.png'; ?>"
               target="_blank" style="text-decoration:none;">
                <img src="<?php echo CMFAQ_PLUGIN_DIR_URL . 'assets/backend/img/cm-faq-pro-statistics.png'; ?>"
                     alt="" style="width:100%; border:1px solid #444;"/>
            </a>
            <span style="font-size:15px;">Statistics</span>
        </div>
    </div>
    <br>
    <h3>Upgrade to Pro for:</h3>
    <ul style="font-size:16px;">
        <li>
            <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor"
                 viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;">
                <path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>
            Tracking views and votes on FAQ questions.
        </li>
        <li>
            <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor"
                 viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;">
                <path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>
            Filtering results by FAQ category or specific time periods.
        </li>
        <li>
            <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor"
                 viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;">
                <path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>
            Improving FAQ content based on user behavior and feedback.
        </li>
    </ul>
    <br>
    <a href="<?php echo admin_url('admin.php?page=cmfaq_pro'); ?>"
       style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>
</div>